package goloader_test

import (
	"context"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/gostafa/reusability/internal/features/typefacts/domain"
	"github.com/gostafa/reusability/internal/features/typefacts/ports/outbound"
	"github.com/gostafa/reusability/internal/infrastructure/goloader"
)

func fixtureDir() string { return filepath.Join("..", "..", "..", "testdata", "fixture") }

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()

	path := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// Black-box: the loader extracts real facts from the fixture module through
// the outbound port.
func TestLoadFixture(t *testing.T) {
	t.Parallel()

	mod, pkgs, err := goloader.New().Load(context.Background(), outbound.FactOptions{
		Directory: fixtureDir(),
		Patterns:  []string{"./..."},
	})
	if err != nil {
		t.Fatal(err)
	}

	if mod != "example.com/fixture" {
		t.Fatalf("module = %q", mod)
	}

	var orders *domain.PackageExtract

	for i := range pkgs {
		if pkgs[i].Path == "example.com/fixture/orders" {
			orders = &pkgs[i]
		}
	}

	if orders == nil {
		t.Fatal("orders package not extracted")
	}

	if !orders.InModule {
		t.Error("orders should be in-module")
	}

	var order *domain.TypeExtract

	for i := range orders.Types {
		if orders.Types[i].Name == "Order" {
			order = &orders.Types[i]
		}
	}

	if order == nil {
		t.Fatal("Order type not extracted")
	}

	if len(order.Methods) != 3 {
		t.Errorf("Order methods = %d, want 3", len(order.Methods))
	}

	if !slices.Contains(order.ReferencedTypeKeys, "example.com/fixture/store.Store") {
		t.Errorf("Order refs = %v, want to include store.Store", order.ReferencedTypeKeys)
	}
}

func TestLoadPackageVarAndConstCounts(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "go.mod", "module example.com/counts\n\ngo 1.23\n")
	writeFile(t, dir, "counts.go", `package counts

var a, b int
var (
	c = 1
	_ = 2
)

const A, B = 1, 2
const (
	C = iota
	_ 
)

func local() {
	var localVar int
	const localConst = 1
	_, _ = localVar, localConst
}
`)
	writeFile(t, dir, "counts_test.go", `package counts

var testVar int
const testConst = 1
`)
	writeFile(t, dir, "generated.go", `// Code generated by test. DO NOT EDIT.

package counts

var generatedVar int
const generatedConst = 1
`)

	_, pkgs, err := goloader.New().Load(context.Background(), outbound.FactOptions{
		Directory: dir,
		Patterns:  []string{"."},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("packages = %d, want 1", len(pkgs))
	}
	if pkgs[0].VarCount != 3 || pkgs[0].ConstCount != 3 {
		t.Fatalf("counts without tests/generated = vars %d consts %d, want 3 and 3",
			pkgs[0].VarCount, pkgs[0].ConstCount)
	}

	_, pkgs, err = goloader.New().Load(context.Background(), outbound.FactOptions{
		Directory:    dir,
		Patterns:     []string{"."},
		IncludeTests: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if pkgs[0].VarCount != 4 || pkgs[0].ConstCount != 4 {
		t.Fatalf("counts with tests = vars %d consts %d, want 4 and 4",
			pkgs[0].VarCount, pkgs[0].ConstCount)
	}

	_, pkgs, err = goloader.New().Load(context.Background(), outbound.FactOptions{
		Directory:        dir,
		Patterns:         []string{"."},
		IncludeGenerated: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if pkgs[0].VarCount != 4 || pkgs[0].ConstCount != 4 {
		t.Fatalf("counts with generated = vars %d consts %d, want 4 and 4",
			pkgs[0].VarCount, pkgs[0].ConstCount)
	}
}

func TestLoadDeclarationDetails(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "go.mod", "module example.com/details\n\ngo 1.23\n")
	writeFile(t, dir, "details.go", `package details

var PublicVar, privateVar int
var _ = 1

const PublicConst = 1
const privateConst = 2

type Widget struct {
	Value int
}

func init() {}

func Exported(x int) int {
	if x > 0 && x < 10 {
		return x
	}
	for i := 0; i < x; i++ {
		x--
	}
	return x
}

func helper() {}

func (w *Widget) Method(x int) int {
	switch x {
	case 1:
		return w.Value
	default:
		return 0
	}
}
`)
	writeFile(t, dir, "details_test.go", `package details

var TestVar int
const TestConst = 1

func TestHelper() {}
`)
	writeFile(t, dir, "generated.go", `// Code generated by test. DO NOT EDIT.

package details

var GeneratedVar int
const GeneratedConst = 1

func GeneratedFunc() {}
`)

	_, pkgs, err := goloader.New().Load(context.Background(), outbound.FactOptions{
		Directory: dir,
		Patterns:  []string{"."},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("packages = %d, want 1", len(pkgs))
	}
	pkg := pkgs[0]
	if got := names(pkg.Variables); !slices.Equal(got, []string{"PublicVar", "privateVar"}) {
		t.Fatalf("variables = %v", got)
	}
	if got := names(pkg.Constants); !slices.Equal(got, []string{"PublicConst", "privateConst"}) {
		t.Fatalf("constants = %v", got)
	}
	if got := functionNames(pkg.Functions); !slices.Equal(got, []string{"init", "Exported", "helper"}) {
		t.Fatalf("functions = %v", got)
	}

	exported := findFunction(t, pkg.Functions, "Exported")
	if exported.Lines != 9 {
		t.Fatalf("Exported lines = %d, want 9", exported.Lines)
	}
	if exported.Branches.Ifs != 1 || exported.Branches.Fors != 1 || exported.Branches.LogicalOps != 1 {
		t.Fatalf("Exported branches = %+v, want if/for/logical = 1", exported.Branches)
	}
	if !exported.Exported || exported.Pos.File != "details.go" || exported.Pos.Line == 0 {
		t.Fatalf("Exported declaration = %+v", exported)
	}

	widget := findTypeExtract(t, pkg.Types, "Widget")
	method := findMethod(t, widget.Methods, "Method")
	if method.Lines != 8 {
		t.Fatalf("Method lines = %d, want 8", method.Lines)
	}
	if method.Branches.Cases != 1 {
		t.Fatalf("Method branches = %+v, want one non-default case", method.Branches)
	}

	_, pkgs, err = goloader.New().Load(context.Background(), outbound.FactOptions{
		Directory:        dir,
		Patterns:         []string{"."},
		IncludeGenerated: true,
		IncludeTests:     true,
	})
	if err != nil {
		t.Fatal(err)
	}
	pkg = pkgs[0]
	if !slices.Contains(names(pkg.Variables), "GeneratedVar") ||
		!slices.Contains(names(pkg.Variables), "TestVar") {
		t.Fatalf("variables with generated/tests = %v", names(pkg.Variables))
	}
	if !slices.Contains(functionNames(pkg.Functions), "GeneratedFunc") ||
		!slices.Contains(functionNames(pkg.Functions), "TestHelper") {
		t.Fatalf("functions with generated/tests = %v", functionNames(pkg.Functions))
	}
}

func names(decls []domain.DeclarationFacts) []string {
	out := make([]string, len(decls))
	for i, d := range decls {
		out[i] = d.Name
	}

	return out
}

func functionNames(functions []domain.FunctionFacts) []string {
	out := make([]string, len(functions))
	for i, fn := range functions {
		out[i] = fn.Name
	}

	return out
}

func findFunction(t *testing.T, functions []domain.FunctionFacts, name string) domain.FunctionFacts {
	t.Helper()

	for _, fn := range functions {
		if fn.Name == name {
			return fn
		}
	}

	t.Fatalf("function %s not found in %v", name, functionNames(functions))

	return domain.FunctionFacts{}
}

func findTypeExtract(t *testing.T, types []domain.TypeExtract, name string) domain.TypeExtract {
	t.Helper()

	for _, typ := range types {
		if typ.Name == name {
			return typ
		}
	}

	t.Fatalf("type %s not found", name)

	return domain.TypeExtract{}
}

func findMethod(t *testing.T, methods []domain.MethodFacts, name string) domain.MethodFacts {
	t.Helper()

	for _, method := range methods {
		if method.Name == name {
			return method
		}
	}

	t.Fatalf("method %s not found", name)

	return domain.MethodFacts{}
}

// Black-box: a pattern matching nothing is an error.
func TestLoadNoMatch(t *testing.T) {
	t.Parallel()

	_, _, err := goloader.New().Load(context.Background(), outbound.FactOptions{
		Directory: fixtureDir(),
		Patterns:  []string{"./does-not-exist"},
	})
	if err == nil {
		t.Fatal("expected error for a pattern matching no packages")
	}
}
